# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1
  - name: Tempo
    orgId: 1

prune: true

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    # port.
    url: http://prometheus:9090
  - name: Loki
    type: loki
    orgId: 1
    # port.
    url: http://loki:3100
  - name: Tempo
    type: tempo
    orgId: 1
    # port.
    url: http://tempo:3200
