version: "3.9"
services:
  application:
    image: docker.io/library/spring-web-application:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
  grafana:
    image: grafana/grafana:11.1.4
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning/
      - ./data/grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v2.53.2
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
  loki:
    image: grafana/loki:2.9.2
    restart: always
    command: ["-config.file=/etc/loki/loki-config.yaml"]
    volumes:
      - ./config/loki:/etc/loki
      - ./data/loki:/loki
  tempo:
    image: grafana/tempo:2.5.0
    restart: always
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./config/tempo:/etc/tempo
      - ./data/tempo:/data/tempo
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.107.0
    restart: always
    command: ["--config", "/etc/otel-collector/config.yaml"]
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - prometheus
      - loki
      - tempo
    volumes:
      - ./config/otel-collector:/etc/otel-collector
